main: com.hotmail.AdrianSR.MiniClanwars.Main
name: SilencioCraftCW
version: 1.0.0
author: AdrianSR
softdepend:
    - Annihilation

commands:
  ClanWars:
    description: ClanWars Commands
    usage: /ClanWars [arguments]
    aliases: [cw, clw, cws]

permissions:
  CW.Set.Lider:
    description: Allow a player to use the comand /cw lider
    default: op
  
  CW.Bypass:
    description: Allow a player to join in the server without clan
    default: op
  
  CW.set.priv:
    description: Allow a player to enable or disable the private mode
    default: op